### ISSUE TITLE
OpenLab Dev 101

### ISSUE THREAD

**Issue by Yikun** [Yikun/yikun.github.com#75]
### 0. 加入OpenLab
根据[Member Application](https://docs.openlabtesting.org/publications/contributors/member-application)指引，加入OpenLab即可，格式可以参考我的[申请Issue](https://github.com/theopenlab/openlab/issues/186)。

### 1. 添加cloud-image的node
```yaml
labels:
  - name: ubuntu-xenial-vxh-arm64
    min-ready: 1

providers:
  - name: vexxhost-openlaballinone
    cloud: vexxhost
    driver: openstack
    image-name-format: 'openlab-{image_name}-{timestamp}'
    launch-timeout: 900
    boot-timeout: 600
    max-concurrency: 10
    cloud-images:
      - name: ubuntu-xenial-vxh-arm64
        username: ubuntu
        image-name: 'de8b384c-5298-48aa-8803-cdb3047ac3a1'
    pools:
      - name: ubuntu-xenial-allinone
        max-ram: 163840
        networks:
          - int-net
        labels:
          - name: ubuntu-xenial-vxh-arm64
            cloud-image: ubuntu-xenial-vxh-arm64
            flavor-name: 'v2-standard-1'
            key-name: allinone-zuul-key
            boot-from-volume: True
            volume-size: 100
```

### 2. Build ARM image
```yaml

# This file is generated by Ansible
#  DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
#
elements-dir: /etc/nodepool/elements
images-dir: /opt/nodepool/images

zookeeper-servers:
  - host: '127.0.0.1'
    port: 2181

labels:
  - name: ubuntu-xenial-vxh-arm64
    min-ready: 0

providers:
  - name: vexxhost-openlaballinone
    cloud: vexxhost
    driver: openstack
    image-name-format: 'armbuild-{image_name}-{timestamp}'
    launch-timeout: 900
    boot-timeout: 600
    max-concurrency: 10
    diskimages:
      - name: ubuntu-xenial-vxh-arm64
        config-drive: true
        pause: False

diskimages:
  - name: ubuntu-xenial-vxh-arm64
    elements:
      - block-device-efi
      - ubuntu-minimal
      - vm
      - simple-init
      - nodepool-base
      - cache-devstack
      - initialize-urandom
      - growroot
      - infra-package-needs
    release: xenial
    env-vars:
      TMPDIR: /opt/dib_tmp
      DIB_CHECKSUM: '1'
      DIB_IMAGE_CACHE: /opt/dib_cache
      DIB_APT_LOCAL_CACHE: '0'
      DIB_DISABLE_APT_CLEANUP: '1'
      DIB_DISTRIBUTION_MIRROR: 'http://mirror.london.linaro-london.openstack.org/ubuntu-ports'
      DIB_DEBOOTSTRAP_EXTRA_ARGS: '--no-check-gpg'
      DIB_DEBIAN_COMPONENTS: 'main,universe'
      GIT_HTTP_LOW_SPEED_TIME: '300'
      GIT_HTTP_LOW_SPEED_LIMIT: '1000'
      ZUUL_USER_SSH_PUBLIC_KEY: '/var/lib/nodepool/.ssh/openlab.ir.pub'

webapp:
  port: 8005
  listen_address: '0.0.0.0'
```
