### ISSUE TITLE
巧用Github Action同步代码到Gitee

### ISSUE THREAD

**Issue by Yikun** [Yikun/yikun.github.com#79]
### 1. 背景
在开源贡献的代码托管的过程中，为了确保我们开源业务的“连续性”，我们有需要将Github的代码同步到其他远端仓库的需求。具体的，对于我们目前参与的项目来说核心诉求是：**以Github社区作为主仓，并且定期自动同步到Gitee作为镜像仓库**。

### 2. 调研
* 结论1: 由于会被Github屏蔽，Gitee的自动同步功能暂时无法支持。
这个问题在Gitee的官方反馈中，[建议github导入的项目能设置定时同步](https://gitee.com/oschina/git-osc/issues/IKH12)提及过，官方的明确答复是不支持。最近又再次和官方渠道求证，由于会被Github屏蔽的关系，这个功能不会被支持。本着有轮子用轮子，没轮子造轮子的原则，我们只能选择**自己实现**。

* 结论2: 靠手动同步存在时效问题，可能会造成部分commit的丢失。
Gitee本身是提供了手动同步功能的，也算比较好用，但是想想看，如果一个组织下面，发展到有几百上千个项目后，这种机制显然无法解决问题了。因此，我们需要**某种计算资源去自动的完成同步**。

* 结论3: 目前我们开源的好几个项目（例如Mindspore, OpenGauss, Kunpeng）都有类似的需求。
作为一个合格的程序员，为了守住DRY(don't repeat yourself，不造重复的轮子)的原则，所以，我们需要实现一个**工具**，同步简单的配置就可以完成多个项目的同步。

最终结论：我们需要**自己实现**一个**工具**，通过**某种计算资源自动的**去完成**周期同步**功能。

### 3. 选型

其实调研结论有了后，我们面对的选型就那么几种：
1. 使用crontab调用脚本周期性同步。这个计算资源得我们自己维护，太重了。排除！
2. 使用Travis、OpenLab等CI资源。这些也可以支持，但是和Github的集成性比较差。
3. Github Action。无缝的和Github集成，处于对新生技术的新鲜感，还是想试一把的，就选他了！

PS：严格来讲，Github Action其实是第二种选择的子集，其实就是单纯的想体验一把，并且把我们的业务需求实现了。

### 4. 实现
Github Action提供了[2种方式](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/about-actions#types-of-actions)去实现Action：
1. Docker container. 这种方式相当于在Github提供的计算资源起个container，在container里面把功能实现。
2. JavaScript. 这种方式相当于在Github提供的计算资源上，直接用JS脚本去实现功能。
作为以后端开发为主的我们，没太多纠结就选择了第一种类型。关于怎么构建一个Github的Action可以参考Github的官方文档[Building actions](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/building-actions)。

https://github.com/Yikun/gitee-mirror-action

### 5. 怎么用呢？
非常简单，只需要2步：
1. 在
2. 新建一个Github workflow。
```yaml
steps:
- name: Mirror the Github organization repos to Gitee.
  uses: Yikun/gitee-mirror-action@master
  with:
    private_key: ${{ secrets.GITEE_PRIVATE_KEY }}
    github_org: kunpengcompute
    gitee_org: kunpengcompute
```
