### ISSUE TITLE
Github Action入门指南

### ISSUE THREAD

**Issue by Yikun** [Yikun/yikun.github.com#83]
## 1. Hello World
我们可以通过repo的action的指引，快速的完成Github action的测试：
![image](https://user-images.githubusercontent.com/1736354/75516372-47a63f00-5a37-11ea-83c5-5520d1586e1b.png)
点击detail后，我们便可以完成Hello world的测试：
![image](https://user-images.githubusercontent.com/1736354/75516468-876d2680-5a37-11ea-80a6-68fc564f96be.png)

可以看到，整个过程非常简单，只需要提交一个位于.github/hello-wrold.yml的文件：
```yml
name: CI
# 在push的时候触发这个workflow
on: [push]
# workflow的job内容
jobs:
  build:
    # 跑job的系统
    runs-on: ubuntu-latest
    # 定义需要跑的脚本
    steps:
    # 使用checkout action
    - uses: actions/checkout@v2
    # Hello World
    - name: Run a one-line script
      run: echo Hello, world!
    # 打印多行
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

我们可以点击detail进入Workflow的[结果页面](https://github.com/Yikun/github-action-tutorial/pull/1/checks?check_run_id=474158198)
![image](https://user-images.githubusercontent.com/1736354/75517029-ac15ce00-5a38-11ea-9f1d-4b004536c91d.png)

```
## 3. 高级功能
